### ISSUE TITLE
composer require problem with dependency 

### ISSUE THREAD

**Issue by PaddyLock** [php-cache/doctrine-bridge#8]
I get the following problem when installing with

composer require cache/psr-6-doctrine-bridge

My minimum stability is 'stable'.

Problem 1
    - cache/psr-6-doctrine-bridge 2.0.1 requires psr/cache-implementation ~1.0 -> no matching package found.
    - cache/psr-6-doctrine-bridge 2.0.0 requires psr/cache-implementation ~1.0 -> no matching package found.
    - Installation request for cache/psr-6-doctrine-bridge ^2.0 -> satisfiable by cache/psr-6-doctrine-bridge[2.0.0, 2.0.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

**Comment by Nyholm** [comment]
You need to install a implementation of PSR cache. Choose any of these: https://packagist.org/providers/psr/cache-implementation
